# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
use_modular_headers!
pod 'FBSDKLoginKit'
pod 'Firebase/Auth'
  # Pods for Runner

end
